import type {Metadata} from "next";
import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";

const fontSans = Plus_Jakarta_Sans({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"],
});

import {cn} from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
    title: "Cureflow",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={cn(
            'min-h-screen bg-dark-300 font-sans antialiased',
            fontSans.variable
        )}><ThemeProvider
            attribute="class"
            defaultTheme="system"
        >
                {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
